// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBuN07140ky7bjYrGUnabEnFhbMMWifnk',
    appId: '1:99841809657:web:a63e20ff644c62a8fbd628',
    messagingSenderId: '99841809657',
    projectId: 'swiftcare-67e76',
    authDomain: 'swiftcare-67e76.firebaseapp.com',
    storageBucket: 'swiftcare-67e76.firebasestorage.app',
    measurementId: 'G-4XWGWN1GQ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNILAzt_KnnXDVg4qp4Yw6Ar-S6DbdFk8',
    appId: '1:99841809657:android:82b5bc8df7bb657ffbd628',
    messagingSenderId: '99841809657',
    projectId: 'swiftcare-67e76',
    storageBucket: 'swiftcare-67e76.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuXHP6gkAXUkwhxN7eHpo_u4XHwk6LrzQ',
    appId: '1:99841809657:ios:6e394e67a38d5abbfbd628',
    messagingSenderId: '99841809657',
    projectId: 'swiftcare-67e76',
    storageBucket: 'swiftcare-67e76.firebasestorage.app',
    iosBundleId: 'com.example.swiftcare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuXHP6gkAXUkwhxN7eHpo_u4XHwk6LrzQ',
    appId: '1:99841809657:ios:6e394e67a38d5abbfbd628',
    messagingSenderId: '99841809657',
    projectId: 'swiftcare-67e76',
    storageBucket: 'swiftcare-67e76.firebasestorage.app',
    iosBundleId: 'com.example.swiftcare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBuN07140ky7bjYrGUnabEnFhbMMWifnk',
    appId: '1:99841809657:web:6a27509168a67a3afbd628',
    messagingSenderId: '99841809657',
    projectId: 'swiftcare-67e76',
    authDomain: 'swiftcare-67e76.firebaseapp.com',
    storageBucket: 'swiftcare-67e76.firebasestorage.app',
    measurementId: 'G-80JCGWGLEX',
  );
}
